[project]
name = "idealista-streamlit"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "streamlit>=1.35",
  "pandas>=2.0",
  "requests>=2.31",
  "python-dotenv>=1.0",
  "openpyxl>=3.1.5",
  "beautifulsoup4>=4.14.3",
  "unidecode>=1.4.0",
  "tenacity>=9.1.2",
]

[tool.uv]
# opcional
